import { Task, University, UserProfile } from "./types";

export const mockUserProfile: UserProfile = {
  fullName: "John Doe",
  email: "john@example.com",
  educationLevel: "Bachelor's Degree",
  degree: "Computer Science",
  graduationYear: "2024",
  gpa: "3.7",
  intendedDegree: "Master's",
  fieldOfStudy: "Computer Science",
  targetIntake: "Fall 2025",
  preferredCountries: ["United States", "Canada", "Germany"],
  budgetRange: "$30,000 - $50,000/year",
  fundingPlan: "Partial scholarship + Self-funded",
  ieltsStatus: "Completed",
  greStatus: "Preparing",
  sopStatus: "Draft in progress",
  onboardingComplete: true,
  currentStage: 2,
};

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Complete GRE Registration",
    description: "Register for the GRE exam and select a test date",
    category: "Exams",
    isCompleted: false,
    dueDate: "2025-02-15",
    priority: "high",
  },
  {
    id: "2",
    title: "Finalize SOP Draft",
    description: "Complete your Statement of Purpose first draft",
    category: "Documents",
    isCompleted: false,
    dueDate: "2025-02-20",
    priority: "high",
  },
  {
    id: "3",
    title: "Research 5 Universities",
    description: "Shortlist at least 5 universities matching your profile",
    category: "Universities",
    isCompleted: true,
    priority: "medium",
  },
  {
    id: "4",
    title: "Request Recommendation Letters",
    description: "Reach out to 3 professors for recommendation letters",
    category: "Documents",
    isCompleted: false,
    dueDate: "2025-03-01",
    priority: "medium",
  },
  {
    id: "5",
    title: "Update Resume",
    description: "Update your resume with recent projects and experiences",
    category: "Documents",
    isCompleted: false,
    priority: "low",
  },
];

export const mockUniversities: University[] = [
  {
    id: "1",
    name: "Stanford University",
    country: "United States",
    city: "Stanford, CA",
    ranking: 3,
    category: "dream",
    tuitionFee: "$58,000/year",
    costLevel: "high",
    acceptanceChance: "low",
    whyItFits: [
      "Strong CS program matching your background",
      "Excellent research opportunities in AI/ML",
      "Strong alumni network in tech industry",
    ],
    risks: [
      "Highly competitive admission (4% acceptance rate)",
      "High tuition cost",
      "Requires exceptional profile",
    ],
    programs: ["MS Computer Science", "MS Artificial Intelligence"],
    deadline: "December 1, 2025",
    isLocked: false,
    isShortlisted: true,
  },
  {
    id: "2",
    name: "University of Toronto",
    country: "Canada",
    city: "Toronto, ON",
    ranking: 21,
    category: "target",
    tuitionFee: "$45,000/year",
    costLevel: "medium",
    acceptanceChance: "medium",
    whyItFits: [
      "Top CS program in Canada",
      "Good fit for your GPA range",
      "Strong AI research department",
    ],
    risks: [
      "Competitive program",
      "Cold climate",
      "High cost of living in Toronto",
    ],
    programs: ["MSc Computer Science", "MASc in Machine Learning"],
    deadline: "January 15, 2025",
    isLocked: true,
    isShortlisted: true,
  },
  {
    id: "3",
    name: "Technical University of Munich",
    country: "Germany",
    city: "Munich",
    ranking: 50,
    category: "target",
    tuitionFee: "$3,000/year",
    costLevel: "low",
    acceptanceChance: "medium",
    whyItFits: [
      "Low tuition fees",
      "Strong engineering reputation",
      "Work opportunities in Europe",
    ],
    risks: [
      "German language may be required for some courses",
      "Bureaucratic admission process",
    ],
    programs: ["MSc Informatics", "MSc Data Engineering"],
    deadline: "May 31, 2025",
    isLocked: false,
    isShortlisted: true,
  },
  {
    id: "4",
    name: "University of British Columbia",
    country: "Canada",
    city: "Vancouver, BC",
    ranking: 34,
    category: "safe",
    tuitionFee: "$40,000/year",
    costLevel: "medium",
    acceptanceChance: "high",
    whyItFits: [
      "Good acceptance rate for your profile",
      "Beautiful campus location",
      "Strong research funding",
    ],
    risks: [
      "High cost of living in Vancouver",
      "Competitive job market locally",
    ],
    programs: ["MSc Computer Science", "MSc Data Science"],
    deadline: "January 31, 2025",
    isLocked: false,
    isShortlisted: true,
  },
  {
    id: "5",
    name: "Georgia Institute of Technology",
    country: "United States",
    city: "Atlanta, GA",
    ranking: 8,
    category: "target",
    tuitionFee: "$32,000/year",
    costLevel: "medium",
    acceptanceChance: "medium",
    whyItFits: [
      "Excellent CS program",
      "More affordable than other US schools",
      "Strong industry connections",
    ],
    risks: [
      "Competitive admission",
      "Large class sizes",
    ],
    programs: ["MS Computer Science", "MS Computational Science"],
    deadline: "February 1, 2025",
    isLocked: false,
    isShortlisted: false,
  },
];

export const STAGES = [
  { id: 1, name: "Building Profile", description: "Complete your profile and get assessed" },
  { id: 2, name: "Discovering Universities", description: "Explore and shortlist universities" },
  { id: 3, name: "Finalizing Universities", description: "Lock your final university choices" },
  { id: 4, name: "Preparing Applications", description: "Complete application requirements" },
];
